version: "3.8"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Maps React dev server to localhost:3000
    environment:
      - REACT_APP_API_URL=http://localhost:5000 # Point client to backend API
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Maps Express server to localhost:5000
    environment:
      - NODE_ENV=development
      - DB_HOST=your-db-host
      - DB_USER=your-db-user
      - DB_PASSWORD=your-db-password
